services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    environment:
      - CASSANDRA_CLUSTER_NAME=UeesCluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    ports:
      - "9042:9042"
    volumes:
      - cassandra1-data:/var/lib/cassandra
    networks:
      - cassandra-net
    healthcheck:
      test: ["CMD-SHELL", "nodetool status || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 4
      start_period: 90s # Le da tiempo de sobra para iniciar sin estresarse

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    environment:
      - CASSANDRA_CLUSTER_NAME=UeesCluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    depends_on:
      cassandra1:
        condition: service_healthy
    ports:
      - "9043:9042"
    volumes:
      - cassandra2-data:/var/lib/cassandra
    networks:
      - cassandra-net

networks:
  cassandra-net:

volumes:
  cassandra1-data:
  cassandra2-data:
